name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create Executable with Pyinstaller
        uses: sayyid5416/pyinstaller-action-windows@v1
        with:
          path: '.'
          spec_file: 'simpleFOCStudio.spec'
          add_data: "src;src"

      - name: Rename file with details
        run: |
          $TAG_NAME = ${{ github.ref_name }} -replace 'refs/tags/', ''
          mv .\dist\windows\simple
