name: Python application with PyInstaller

on: 
  push:
    branches: [ testgui ]

jobs:
  build_windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      
      - name: Create Executable with PyInstaller
        run: pyinstaller simpleFOCStudio.spec
      
      - name: Rename file with details
        run: |
          Move-Item -Path .\dist\simpleFOCStudio.exe -Destination .\dist\simpleFOCStudio-windows-x86_64-${{ github.sha }}.exe
        shell: pwsh

      - name: Create Release Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          TAG_NAME=$(echo ${GITHUB_REF#refs/heads/testgui}-$(date +%Y%m%d%H%M%S))
          echo "::set-env name=TAG_NAME::$TAG_NAME"
          git tag $TAG_NAME
          git push origin $TAG_NAME
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/*.exe
          tag_name: ${{ env.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
