name: Python application with PyInstaller

on: 
  push:
    branches: [ testgui ]

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Create Executable with PyInstaller
        run: pyinstaller simpleFOCStudio.spec

      - name: Rename file with details
        run: |
          Move-Item -Path .\dist\windows\simpleFOCStudio.exe -Destination .\dist\windows\simpleFOCStudio-windows-x86_64-${{ github.ref_name }}.exe

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/windows/**
